# Generated by Django 4.2.6 on 2023-10-23 15:08

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(0, message='Мы деньги за игры не даём!')], verbose_name='цена')),
                ('poster', models.ImageField(blank=True, default='posters/default_game.png', upload_to='posters', verbose_name='постер')),
                ('rate', models.FloatField(blank=True, default=0, max_length=5, null=True, verbose_name='рэйтинг')),
                ('quantity', models.IntegerField(blank=True, default=0, verbose_name='количество')),
            ],
            options={
                'verbose_name': 'игра',
                'verbose_name_plural': 'игры',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='UserGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game', verbose_name='игра')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
        ),
        migrations.CreateModel(
            name='Subscripe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('datetime_finished', models.DateField(default=datetime.datetime(2023, 11, 22, 21, 8, 9, 933310), verbose_name='Дата завершения')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='GameComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, validators=[django.core.validators.MinValueValidator(0, message='Ваш текст пустой!')], verbose_name='текст')),
                ('is_delete', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='games.game', verbose_name='игра')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'комментрий',
                'verbose_name_plural': 'комментрии',
                'ordering': ('-id',),
            },
        ),
    ]
