# Generated by Django 4.2.5 on 2023-09-25 13:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(0, message='Мы деньги за игры не даём!')], verbose_name='цена')),
                ('poster', models.ImageField(default=1, upload_to='posters', verbose_name='постер')),
                ('rate', models.FloatField(default=0, max_length=5, verbose_name='рэйтиннг')),
                ('comment', models.ManyToManyField(related_name='game', to=settings.AUTH_USER_MODEL, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'игра',
                'verbose_name_plural': 'игры',
                'ordering': ('-id',),
            },
        ),
    ]
