# Generated by Django 4.2.5 on 2023-09-25 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='comment',
            field=models.ManyToManyField(max_length=200, related_name='game', to=settings.AUTH_USER_MODEL, verbose_name='комментарий'),
        ),
    ]
