# Generated by Django 4.2.5 on 2023-09-25 14:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0002_alter_game_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='comment',
        ),
        migrations.CreateModel(
            name='GameComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, validators=[django.core.validators.MinValueValidator(0, message='Ваш текст пустой!')], verbose_name='текст')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='games.game', verbose_name='игра')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'комментрий',
                'verbose_name_plural': 'комментрии',
                'ordering': ('-id',),
            },
        ),
    ]
