# Generated by Django 4.2.5 on 2023-09-25 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_game_comment_gamecomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('id',), 'verbose_name': 'игра', 'verbose_name_plural': 'игры'},
        ),
    ]
