# Generated by Django 4.2.5 on 2023-09-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_game_comment_gamecomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('id',), 'verbose_name': 'игра', 'verbose_name_plural': 'игры'},
        ),
        migrations.AddField(
            model_name='game',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='game',
            name='poster',
            field=models.ImageField(blank=True, default='posters/default_game.png', upload_to='posters', verbose_name='постер'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rate',
            field=models.FloatField(blank=True, default=0, max_length=5, verbose_name='рэйтиннг'),
        ),
    ]
