# Generated by Django 4.2.5 on 2023-09-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='game',
            name='poster',
            field=models.ImageField(blank=True, default='posters/default_game.png', upload_to='posters', verbose_name='постер'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rate',
            field=models.FloatField(blank=True, default=0, max_length=5, verbose_name='рэйтиннг'),
        ),
    ]
