# Generated by Django 4.2.5 on 2023-09-29 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_options_game_quantity_alter_game_poster_and_more'),
        ('games', '0005_game_quantity_alter_game_poster_alter_game_rate'),
    ]

    operations = [
    ]
